#coding: utf8

# This file was *autogenerated* from the file play-with-sage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1)#!/usr/bin/sage

# from sage.manifolds.operators import *

# E = EuclideanSpace(3)

x, y = var('x y')

__tmp__=var("x,y"); f = symbolic_expression(x ** _sage_const_2  + x * y).function(x,y)
# f = E.scalar_field(x ** 2 + x * y, name='f')

print("f = {}".format(f))
print("∂f/∂x = {}".format(f.diff(x)))
print("∇f = {}".format(f.gradient()))

print("f(1, 2) = {}".format(f(_sage_const_1 , _sage_const_2 )))
a = [_sage_const_1 , _sage_const_2 ]
print("f({}) = {}".format(a, f(a)))
print("f({}) = {}".format(a, f(*a)))

